- name: Demo on Variables on Play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Variable
      debug:
        msg: URL = {{URL}}
        # In ansible we access the variable in two flower braces.
    - name: Print Variable from Task Declaration
      vars:
        URL: task.google.com
      ## You can declare variable on task level, which the scope of this variable is only on task level.
      debug:
        msg: URL = {{URL}}

