- name: Demo on Variables on Play
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Variable
      debug:
        msg: URL = {{URL}}
        # In ansible we access the variable in two flower braces.


