- name: Roboshop Project Setup with Ansible
  hosts: all
  become: yes
  ## become also can be given at task level, But it applies only to that task. Giving at play level will be applicable to all the tasks.
  roles:
    - frontend
    - catalogue
