- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add RoboShop App User
  user:
    name: roboshop

- name: Include AZ CLI Installation Steps
  include_role:
    name: common
    tasks_from: az-cli-setup